// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ2gfyVwBn4SuqOq9jTD7CmI7rMLIoPms',
    appId: '1:554416796284:android:cb5ecd4ed4927254ebcff9',
    messagingSenderId: '554416796284',
    projectId: 'flutter-ic-lydia-ryan',
    storageBucket: 'flutter-ic-lydia-ryan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD04-d6onRVCgj3jALEXrLkswUiBkIDtB8',
    appId: '1:554416796284:ios:8ef7369a12daacc7ebcff9',
    messagingSenderId: '554416796284',
    projectId: 'flutter-ic-lydia-ryan',
    storageBucket: 'flutter-ic-lydia-ryan.appspot.com',
    iosClientId:
        '554416796284-r2q6j3ser1qe5r8fehob053c3pk2r2ub.apps.googleusercontent.com',
    iosBundleId: 'com.lydiaryan.fluttersurvey.staging',
  );
}
