name: iOS - Deploy production build to Firebase

on:
  push:
    branches:
      - develop
      - chore/51-ios-distribution-to-firebase

jobs:
  build_and_deploy_ios_production_to_firebase:
    name: Build & Deploy iOS production to Firebase
    runs-on: macOS-latest
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.7.11'

      - name: Setup .env for production
        env:
          ENV_PRODUCTION: ${{ secrets.ENV_PRODUCTION }}
        run: |
          echo $ENV_PRODUCTION > .env

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Run code generator.
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Install iOS dependencies
        run: cd ./ios && bundle install && bundle exec pod install

      - name: Match AppStore
        run: cd ./ios && bundle exec fastlane sync_appstore_production_signing

      - name: Deploy to Firebase App Distribution
        run: cd ./ios && bundle exec fastlane build_and_upload_to_firebase
        env:
          FIREBASE_IOS_APP_ID: ${{ secrets.FIREBASE_IOS_APP_ID_PRODUCTION }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          BUILD_NUMBER: $GITHUB_RUN_NUMBER
